add separate markdown and html outputs

diff --git a/lit b/lit
--- a/lit
+++ b/lit
@@ -11,31 +11,37 @@ fail() {
 usage() {
     cat >&2 <<EOF
 $1
-usage: lit [options] file1 [file2 ...]
+usage: lit [options] format file1 [file2 ...]
 
 options:
     -m extra-meta-html-file (e.g. stylesheets, open graph meta)
     -h extra-header-html-file (e.g. site banner)
-    -f extra-footer-html-file (e.g. site links)
+    -f extra-footer-html-file (e.g. script tags, site links)
     -o output-directory
+
+output formats:
+    markdown (html flags have no effect)
+    html
 
 description:
     input files may contain markdown or source code
 
     lit translates source code to markdown and concatenates
-    the result of each file into a single document index.md
+    the result of each input file into a single document,
+    optionally converting to HTML and constructing a complete
+    web page together with any HTML content provided via
+    command line options
 
-    this file is converted to HTML and embedded in index.html
-    which is constructed to contain a single article and any
-    content given through command line options
+    the output file is named index.md or index.html and is
+    written to the current working directory by default
 
     input files may contain directives that prompt lit to e.g.
     build and run programs, piping the output into the markdown
     document
 
     any site assets generated by these programs should be
-    written to relative paths so that lit can control where they
-    end up by changing the working directory
+    written to the current working directory so lit can detect
+    them
 EOF
     exit 1
 }
@@ -46,28 +52,84 @@ recurse() {
 
 dotest() {
     [ -d ./tests ] || fail "test directory does not exist"
-    echo "running tests"
     outdir=/tmp/lit.out.d
-    for testin in $(find ./tests -mindepth 1 -maxdepth 1 -name '*.out' -prune -o -print)
+    mkdir -p $outdir
+    echo "running tests"
+    for testin in $(find ./tests -mindepth 1 -maxdepth 1 -name '*.html' -o -name "*.md" -prune -o -print)
     do
-        [ -d $outdir ] && rm -r $outdir
-        mkdir /tmp/lit.out.d
-        testout=$testin.out
+        if [ -d "$testin" ]
+        then
+            testargs=( $(find "$testin" -mindepth 1 -maxdepth 1 -type f) )
+        else
+            testargs=( "$testin" )
+        fi
         if [ "$1" == "generate" ]
         then
-            echo "generating $testout"
-            recurse -o $outdir "$testin"
-            cp $outdir/index.html "$testout"
-        elif [ ! -f "$testout" ]
+            echo "generating $testin.md and $testin.html"
+            recurse -o $outdir markdown "${testargs[@]}"
+            recurse -o $outdir html "${testargs[@]}"
+            cp $outdir/index.md "$testin.md"
+            cp $outdir/index.html "$testin.html"
+        elif [ ! -f "$testin.md" ]
         then
-            fail "expected test output not found: $testout"
+            fail "expected test output not found: $testin.md"
+        elif [ ! -f "$testin.html" ]
+        then
+            fail "expected test output not found: $testin.html"
         else
             echo "running $testin"
-            recurse -o $outdir "$testin"
-            diff "$testout" $outdir/index.html || fail "failed test: $testin"
+            recurse -o $outdir markdown "${testargs[@]}"
+            recurse -o $outdir html "${testargs[@]}"
+            diff "$testin.md" $outdir/index.md || fail "failed test: $testin"
+            diff "$testin.html" $outdir/index.html || fail "failed test: $testin"
         fi
     done
     echo "all tests passed"
+}
+
+domarkdown() {
+    awk -f "$pscripts/lit-utils.awk" -f "$pscripts/lit-main.awk" "$@"
+}
+
+dohtml() {
+    cat <<EOF
+<!doctype html>
+
+<html lang="en">
+<head>
+    <meta charset="utf-8">
+    <meta name="viewport" content="width=device-width, initial-scale=1">
+EOF
+
+    [ -f "$pmeta" ] && cat "$pmeta"
+
+    awk -f "$pscripts/lit-utils.awk" -f "$pscripts/lit-meta.awk" "${pfiles[@]}"
+
+    cat <<EOF
+</head>
+<body>
+EOF
+
+    [ -f "$pheader" ] && cat "$pheader"
+
+    cat <<EOF
+<main>
+<article>
+EOF
+
+    domarkdown "$@" | md2html
+
+    cat <<EOF
+</article>
+</main>
+EOF
+
+    [ -f "$pfooter" ] && cat "$pfooter"
+
+    cat <<EOF
+</body>
+</html>
+EOF
 }
 
 ptest=
@@ -97,6 +159,8 @@ then
 fi
 
 shift $(( OPTIND - 1 ))
+pformat="$1"
+shift
 pfiles=( "$@" )
 
 if [ ${#pfiles[@]} -eq 0 ]
@@ -106,43 +170,12 @@ fi
 
 [ -d "$pdir" ] || mkdir "$pdir"
 
-cat > "$pdir/index.html" <<EOF
-<!doctype html>
-
-<html lang="en">
-<head>
-    <meta charset="utf-8">
-    <meta name="viewport" content="width=device-width, initial-scale=1">
-EOF
-
-[ -f "$pmeta" ] && cat "$pmeta" >> "$pdir/index.html"
-
-awk -f "$pscripts/lit-utils.awk" -f "$pscripts/lit-meta.awk" "${pfiles[@]}" >> "$pdir/index.html"
-
-cat >> "$pdir/index.html" <<EOF
-</head>
-<body>
-EOF
-
-[ -f "$pheader" ] && cat "$pheader" >> "$pdir/index.html"
-
-cat >> "$pdir/index.html" <<EOF
-<main>
-<article>
-EOF
-
-awk -f "$pscripts/lit-utils.awk" -f "$pscripts/lit-main.awk" "${pfiles[@]}" | \
-    tee "$pdir/index.md" | \
-    md2html >> "$pdir/index.html"
-
-cat >> "$pdir/index.html" <<EOF
-</article>
-</main>
-EOF
-
-[ -f "$pfooter" ] && cat "$pfooter" >> "$pdir/index.html"
-
-cat >> "$pdir/index.html" <<EOF
-</body>
-</html>
-EOF
+if [ "$pformat" == "html" ]
+then
+    dohtml "${pfiles[@]}" > "$pdir/index.html"
+elif [ "$pformat" == "markdown" ]
+then
+    domarkdown "${pfiles[@]}" > "$pdir/index.md"
+else
+    fail "unknown format: $pformat"
+fi
